apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-07-03T04:47:40Z"
  generation: 1
  labels:
    app: abc
  name: abc
  namespace: development
  resourceVersion: "28692"
  selfLink: /apis/extensions/v1beta1/namespaces/development/deployments/abc
  uid: 4d334c11-f07e-4215-b6c5-c1d1beee7377
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: abc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: abc
    spec:
      containers:
      - image: aipine:latest
        imagePullPolicy: Always
        name: aipine
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-07-03T04:47:40Z"
    lastUpdateTime: "2019-07-03T04:47:40Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-07-03T04:47:40Z"
    lastUpdateTime: "2019-07-03T04:47:40Z"
    message: ReplicaSet "abc-6bc78cd6cb" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
