apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-replica
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-replica
  template:
    metadata:
      labels:
        app: my-replica
    spec:
      containers:
      - name: nginx-rs
        image: nginx
        livenessProbe:
          httpGet:
            path: /
            port: 80
        lifecycle:
          preStop:
            exec:
              command: [
                # Gracefully shutdown nginx
                "/usr/sbin/nginx", "-s", "quit"
              ]
