apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-replica
  namespace: development
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-replica
  template:
    metadata:
      labels:
        app: my-replica
    spec:
      containers:
      - name: nginx-rs
        image: nginx:latest
