apiVersion: v1
kind: ResourceQuota
metadata:
  name: devlopement-quota
  namespace: development
spec:
  hard:
    pods: "3"
    # 1 core = 1000 millicores
    cpu: "800m"
    memory: "750Mi"
    replicaset: "2"
    deployment: "1"
