apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample
spec:
  containers:
  - name: sample-container
    image: nginx:latest
    resources:
     # This will be intial amount of resources allocated to the POD when its created
      requests:
        cpu: "300m"
        memory: "100Mi"
     # This will be tbe maximum amount of resources your POD can claim
      limits:
        cpu: "325m"
        memory: "175Mi"
